.Dd August 8, 2022
.Dt AUTOLAYOUT 1
.Sh NAME
.Nm autolayout
.Nd automatically change the layout of i3 based on the width and height of the focused window
.Sh SYNOPSIS
.Nm
.Op Fl bhv
.Sh DESCRIPTION
The
.Nm
utility changes the i3 layout when the focused window changes.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl b
run autolayout in the background
.It Fl h
show usage
.It Fl v
display the program version
.El
.Sh CONFIGURATION
.Bl -tag -width indent
.It add this line to your i3 configuration file to start autolayout when i3 starts
exec_always --no-startup-id autolayout -b
.El
.Sh SEE ALSO
.Xr i3 1
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/autolayout/issues
