.TH AUTOLAYOUT 1 "February 15, 2022"
.SH NAME
autolayout \- automatically change the layout of i3 based on the width and height of the focused window.
.SH SYNOPSIS
\fBautolayout\fP [ --daemon ]
.SH OPTIONS
\fB--daemon\fP run autolayout in the background as a daemon
.SH BUGS
report bugs here: https://github.com/alpheratz0/autolayout/issues
